"""Add es_nodo_raiz

Revision ID: 415e015ac848
Revises: dd1bfcf8d1cb
Create Date: 2026-09-23 05:31:49.915034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '415e015ac848'
down_revision: Union[str, Sequence[str], None] = 'dd1bfcf8d1cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodos_flujo', sa.Column('es_nodo_raiz', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodos_flujo', 'es_nodo_raiz')
    # ### end Alembic commands ###
