"""Add rol to usuario

Revision ID: 7cdc1cc8a22d
Revises: 2b877c0eddd3
Create Date: 2026-09-28 21:23:35.481419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7cdc1cc8a22d'
down_revision: Union[str, Sequence[str], None] = '2b877c0eddd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('rol', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'rol')
    # ### end Alembic commands ###
