"""Migracion inicial a MySQL

Revision ID: a16cccaf3924
Revises: 
Create Date: 2026-09-18 22:13:25.899324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a16cccaf3924'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('correo', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_correo'), 'admins', ['correo'], unique=True)
    op.create_index(op.f('ix_admins_id'), 'admins', ['id'], unique=False)
    op.create_table('casos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('mensaje', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_casos_estado'), 'casos', ['estado'], unique=False)
    op.create_index(op.f('ix_casos_id'), 'casos', ['id'], unique=False)
    op.create_index(op.f('ix_casos_tipo'), 'casos', ['tipo'], unique=False)
    op.create_table('configuraciones',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('clave', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('valor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuraciones_clave'), 'configuraciones', ['clave'], unique=True)
    op.create_index(op.f('ix_configuraciones_id'), 'configuraciones', ['id'], unique=False)
    op.create_table('nodos_flujo',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('codigo', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('contenido', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bandeja_destino', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('posicion_x', sa.Integer(), nullable=False),
    sa.Column('posicion_y', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_index(op.f('ix_nodos_flujo_id'), 'nodos_flujo', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('dni', sqlmodel.sql.sqltypes.AutoString(length=9), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_dni'), 'usuarios', ['dni'], unique=True)
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('documentos_identidad',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('tipo_documento', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('ruta_archivo', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('texto_extraido', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('validado', sa.Boolean(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documentos_identidad_id'), 'documentos_identidad', ['id'], unique=False)
    op.create_index(op.f('ix_documentos_identidad_usuario_id'), 'documentos_identidad', ['usuario_id'], unique=False)
    op.create_table('historial_cambios_flujo',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('admin_id', sa.Uuid(), nullable=False),
    sa.Column('nodo_id', sa.Uuid(), nullable=False),
    sa.Column('tipo_cambio', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('datos_anteriores', sa.Text(), nullable=True),
    sa.Column('datos_nuevos', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['nodo_id'], ['nodos_flujo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historial_cambios_flujo_admin_id'), 'historial_cambios_flujo', ['admin_id'], unique=False)
    op.create_index(op.f('ix_historial_cambios_flujo_id'), 'historial_cambios_flujo', ['id'], unique=False)
    op.create_index(op.f('ix_historial_cambios_flujo_nodo_id'), 'historial_cambios_flujo', ['nodo_id'], unique=False)
    op.create_table('logs_auditoria',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=True),
    sa.Column('accion', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('detalles', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_auditoria_id'), 'logs_auditoria', ['id'], unique=False)
    op.create_index(op.f('ix_logs_auditoria_usuario_id'), 'logs_auditoria', ['usuario_id'], unique=False)
    op.create_table('opciones_flujo',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nodo_origen_id', sa.Uuid(), nullable=False),
    sa.Column('nodo_destino_id', sa.Uuid(), nullable=False),
    sa.Column('etiqueta', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('valor_entrada', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('condicion', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['nodo_destino_id'], ['nodos_flujo.id'], ),
    sa.ForeignKeyConstraint(['nodo_origen_id'], ['nodos_flujo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opciones_flujo_id'), 'opciones_flujo', ['id'], unique=False)
    op.create_index(op.f('ix_opciones_flujo_nodo_destino_id'), 'opciones_flujo', ['nodo_destino_id'], unique=False)
    op.create_index(op.f('ix_opciones_flujo_nodo_origen_id'), 'opciones_flujo', ['nodo_origen_id'], unique=False)
    op.create_table('sesiones_chat',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('nodo_actual_id', sa.Uuid(), nullable=True),
    sa.Column('contexto', sa.JSON(), nullable=False),
    sa.Column('historial_nodos', sa.JSON(), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('iniciada_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ultima_interaccion', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['nodo_actual_id'], ['nodos_flujo.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sesiones_chat_id'), 'sesiones_chat', ['id'], unique=False)
    op.create_index(op.f('ix_sesiones_chat_nodo_actual_id'), 'sesiones_chat', ['nodo_actual_id'], unique=False)
    op.create_index(op.f('ix_sesiones_chat_usuario_id'), 'sesiones_chat', ['usuario_id'], unique=False)
    op.create_table('tokens_acceso',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expiracion', sa.DateTime(), nullable=False),
    sa.Column('revocado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tokens_acceso_id'), 'tokens_acceso', ['id'], unique=False)
    op.create_index(op.f('ix_tokens_acceso_token'), 'tokens_acceso', ['token'], unique=True)
    op.create_index(op.f('ix_tokens_acceso_usuario_id'), 'tokens_acceso', ['usuario_id'], unique=False)
    op.create_table('mensajes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sesion_id', sa.Uuid(), nullable=False),
    sa.Column('remitente', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('contenido', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sesion_id'], ['sesiones_chat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mensajes_id'), 'mensajes', ['id'], unique=False)
    op.create_index(op.f('ix_mensajes_sesion_id'), 'mensajes', ['sesion_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mensajes_sesion_id'), table_name='mensajes')
    op.drop_index(op.f('ix_mensajes_id'), table_name='mensajes')
    op.drop_table('mensajes')
    op.drop_index(op.f('ix_tokens_acceso_usuario_id'), table_name='tokens_acceso')
    op.drop_index(op.f('ix_tokens_acceso_token'), table_name='tokens_acceso')
    op.drop_index(op.f('ix_tokens_acceso_id'), table_name='tokens_acceso')
    op.drop_table('tokens_acceso')
    op.drop_index(op.f('ix_sesiones_chat_usuario_id'), table_name='sesiones_chat')
    op.drop_index(op.f('ix_sesiones_chat_nodo_actual_id'), table_name='sesiones_chat')
    op.drop_index(op.f('ix_sesiones_chat_id'), table_name='sesiones_chat')
    op.drop_table('sesiones_chat')
    op.drop_index(op.f('ix_opciones_flujo_nodo_origen_id'), table_name='opciones_flujo')
    op.drop_index(op.f('ix_opciones_flujo_nodo_destino_id'), table_name='opciones_flujo')
    op.drop_index(op.f('ix_opciones_flujo_id'), table_name='opciones_flujo')
    op.drop_table('opciones_flujo')
    op.drop_index(op.f('ix_logs_auditoria_usuario_id'), table_name='logs_auditoria')
    op.drop_index(op.f('ix_logs_auditoria_id'), table_name='logs_auditoria')
    op.drop_table('logs_auditoria')
    op.drop_index(op.f('ix_historial_cambios_flujo_nodo_id'), table_name='historial_cambios_flujo')
    op.drop_index(op.f('ix_historial_cambios_flujo_id'), table_name='historial_cambios_flujo')
    op.drop_index(op.f('ix_historial_cambios_flujo_admin_id'), table_name='historial_cambios_flujo')
    op.drop_table('historial_cambios_flujo')
    op.drop_index(op.f('ix_documentos_identidad_usuario_id'), table_name='documentos_identidad')
    op.drop_index(op.f('ix_documentos_identidad_id'), table_name='documentos_identidad')
    op.drop_table('documentos_identidad')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_dni'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_nodos_flujo_id'), table_name='nodos_flujo')
    op.drop_table('nodos_flujo')
    op.drop_index(op.f('ix_configuraciones_id'), table_name='configuraciones')
    op.drop_index(op.f('ix_configuraciones_clave'), table_name='configuraciones')
    op.drop_table('configuraciones')
    op.drop_index(op.f('ix_casos_tipo'), table_name='casos')
    op.drop_index(op.f('ix_casos_id'), table_name='casos')
    op.drop_index(op.f('ix_casos_estado'), table_name='casos')
    op.drop_table('casos')
    op.drop_index(op.f('ix_admins_id'), table_name='admins')
    op.drop_index(op.f('ix_admins_correo'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
