"""Add ticket column to casos

Revision ID: b107969a459c
Revises: 4645ae80d9ee
Create Date: 2026-09-28 20:26:29.818504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b107969a459c'
down_revision: Union[str, Sequence[str], None] = '4645ae80d9ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('casos', sa.Column('ticket', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    op.create_index(op.f('ix_casos_ticket'), 'casos', ['ticket'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_casos_ticket'), table_name='casos')
    op.drop_column('casos', 'ticket')
    # ### end Alembic commands ###
