"""Add tracking and admin fields

Revision ID: b23df60f9c67
Revises: 7cdc1cc8a22d
Create Date: 2026-09-29 14:13:07.817838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b23df60f9c67'
down_revision: Union[str, Sequence[str], None] = '7cdc1cc8a22d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False))
    op.add_column('admins', sa.Column('rol', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False))
    op.add_column('casos', sa.Column('codigo_ticket', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True))
    op.add_column('casos', sa.Column('finalizado_en', sa.DateTime(timezone=True), nullable=True))
    op.add_column('casos', sa.Column('atendido_por', sa.Uuid(), nullable=True))
    op.drop_index(op.f('ix_casos_ticket'), table_name='casos')
    op.create_index(op.f('ix_casos_atendido_por'), 'casos', ['atendido_por'], unique=False)
    op.create_index(op.f('ix_casos_codigo_ticket'), 'casos', ['codigo_ticket'], unique=True)
    op.create_foreign_key('fk_casos_atendido_por_admins', 'casos', 'admins', ['atendido_por'], ['id'])
    op.drop_column('casos', 'ticket')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('casos', sa.Column('ticket', mysql.VARCHAR(length=20), nullable=True))
    op.drop_constraint('fk_casos_atendido_por_admins', 'casos', type_='foreignkey')
    op.drop_index(op.f('ix_casos_codigo_ticket'), table_name='casos')
    op.drop_index(op.f('ix_casos_atendido_por'), table_name='casos')
    op.create_index(op.f('ix_casos_ticket'), 'casos', ['ticket'], unique=False)
    op.drop_column('casos', 'atendido_por')
    op.drop_column('casos', 'finalizado_en')
    op.drop_column('casos', 'codigo_ticket')
    op.drop_column('admins', 'rol')
    op.drop_column('admins', 'nombre')
    # ### end Alembic commands ###
