"""Add nota_cierre to Caso

Revision ID: c2f4fb540ccf
Revises: b23df60f9c67
Create Date: 2026-09-29 22:12:40.496800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c2f4fb540ccf'
down_revision: Union[str, Sequence[str], None] = 'b23df60f9c67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('casos', sa.Column('nota_cierre', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('casos', 'nota_cierre')
    # ### end Alembic commands ###
