"""Add sesion_id to casos

Revision ID: df22b06028df
Revises: b107969a459c
Create Date: 2026-09-28 20:45:20.942408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'df22b06028df'
down_revision: Union[str, Sequence[str], None] = 'b107969a459c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('casos', sa.Column('sesion_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_casos_sesion_id'), 'casos', ['sesion_id'], unique=False)
    op.create_foreign_key(None, 'casos', 'sesiones_chat', ['sesion_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'casos', type_='foreignkey')
    op.drop_index(op.f('ix_casos_sesion_id'), table_name='casos')
    op.drop_column('casos', 'sesion_id')
    # ### end Alembic commands ###
